# frozen_string_literal: true

workspace 'RxReachability_Example.xcworkspace'
platform :ios, '10.0'

install!  'cocoapods',
          :generate_multiple_pod_projects => true,
          :incremental_installation => true,
          :share_schemes_for_development_pods => true,
          :deterministic_uuids => true,
          :lock_pod_sources => false,
          :preserve_pod_file_structure => true

target 'RxReachability_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxReachability
  pod 'RxReachability', 
      :path => '../',
      :inhibit_warnings => false,
      :appspecs => ['RxReachabilityExample'],
      :testspecs => [ 'RxReachabilityTests' ]
end
