# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Test, lint pod and Build carthage."
  lane :test do
    test_example
    pod_lint
    carthage_build
  end

  desc "Cocoapods lint the pod for all platforms"
  private_lane :pod_lint do
    pod_lib_lint(allow_warnings: true)
  end

  desc "Test the example project"
  private_lane :test_example do  
    cocoapods(podfile: "./Example/Podfile")
    scan(workspace: "./Example/RxReachability.xcworkspace",
              scheme: "RxReachability-Example"
            )
  end

  desc "Carthage"
  private_lane :carthage_build do
  end

end
